### PR TITLE
fix(audioplayers_platform_interface): handle platform exception via logger

### LINKED ISSUE #1253: Floating promise
Found a floating promise in https://github.com/bluefireteam/audioplayers/blob/ff78a42f842e146df7dc98d6d00ae27821355653/packages/audioplayers_platform_interface/lib/method_channel_audioplayers_platform.dart#L147

It results in not being able to catch errors.

Will do a PR.

### PR DESCRIPTION
**Pull request by larssn**
# Description

Fixes a floating promise

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:`, `chore:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation and added dartdoc comments with `///`, where necessary.
- [x] I have updated/added relevant examples in [example].

## Breaking Change

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

## Related Issues

Fixes #1253

[issue database]: https://github.com/bluefireteam/audioplayers/issues
[Contributor Guide]: https://github.com/bluefireteam/audioplayers/blob/main/contributing.md#feature-requests--prs
[Conventional Commit]: https://conventionalcommits.org
[example]: https://github.com/bluefireteam/audioplayers/tree/main/packages/audioplayers/example

### CODE REVIEW

**Comment by Gustl22** [comment]
Do you have one example error / forced native error to quickly test the difference? Thank you!

**Comment by larssn** [comment]
Well there's an error that's been showing up in the last few months in our error reporting service which is:
`MediaPlayer error with what:MEDIA_ERROR_UNKNOWN {what:1} extra:MEDIA_ERROR_SYSTEM`
from
```
method_channel_audioplayers_platform.dart in MethodChannelAudioplayersPlatform._doHandlePlatformCall at line 174 within audioplayers_platform_interface
method_channel_audioplayers_platform.dart in MethodChannelAudioplayersPlatform.platformCallHandler at line 147 within audioplayers_platform_interface
```

I've been able to reproduce it by spamming the same audiofile in a click handler, which seems to overwhelm something, and then the error above is thrown.

We're already try/catching playing the audio, and are not interested in the exception in our error reporting service. But since it's a floating promise, the catch clause won't work.

The current catch clause that it's in won't work, and `_logger.error('Unexpected error: $ex');` won't ever run.

**Review by Gustl22 — CHANGES_REQUESTED** [review]
Ok I tested, but the error is still not logged. I think this was my fault during #1132, by only catching "Exceptions" but no objects.

I would propose something like this:
- remove unnecessary async keyword
- differentiate native platform errors and interface errors

```
  Future<void> platformCallHandler(MethodCall call) async {
    try {
      _doHandlePlatformCall(call);
    } on Exception catch (ex) {
      _logger.error('Unexpected error: $ex');
    }
  }

  void _doHandlePlatformCall(MethodCall call) {
    final playerId = call.getString('playerId');

    switch (call.method) {
      case 'audio.onDuration':
        final millis = call.getInt('value');
        final duration = Duration(milliseconds: millis);
        emitDuration(playerId, duration);
        break;
      case 'audio.onCurrentPosition':
        final millis = call.getInt('value');
        final position = Duration(milliseconds: millis);
        emitPosition(playerId, position);
        break;
      case 'audio.onComplete':
        emitComplete(playerId);
        break;
      case 'audio.onSeekComplete':
        emitSeekComplete(playerId);
        break;
      case 'audio.onError':
        _logger.error(
            'Unexpected platform error: ${call.getString('value')}');
        break;
      default:
        _logger.error('Unknown method ${call.method} ');
    }
  }
```

**Comment by larssn** [comment]
I'm fine with anything tbh, as long as we don't leak floating promises. 🙂

**Comment by larssn** [comment]
You want me to make the suggested changes btw?

**Comment by Gustl22** [comment]
> You want me to make the suggested changes btw?

That would be nice, in case you agree with them.

**Comment by larssn** [comment]
The only real difference with your suggestion is that sometimes it logs `_logger.error('Unexpected platform error: ${call.getString('value')}');` and sometimes it logs `_logger.error('Unexpected error: $ex');`, neither of which the consumer of this package really cares about, and if they do, they can raise an issue with the error, irregardless of it being a platform error or interface error.

As I see it, the `await` in the OP should do the trick, as that will allow unknown exceptions to be caught in the first place, as opposed to not.

**Comment by Gustl22** [comment]
> As I see it, the await in the OP should do the trick, as that will allow unknown exceptions to be caught in the first place, as opposed to not.

No need to make it `async`. I removed the Future from `_doHandlePlatformCall`. So we can also ditch the `await`.
Also the error is not logged non the less, if only catching `Exceptions` and not all `Object`s. But we don't have to, if logging the platform error beforehand.

**Comment by larssn** [comment]
True true, but non-`Exception` exceptions are rare (hopefully).

You want me to test the above change? I haven't really set up a test env. I'm generally pretty pressed for time. Wondering if you would mind doing the test?

**Comment by Gustl22** [comment]
I already tested my implementation. Yours does not log the objects, which would have need to be wrapped inside a `Exception` which - like said - was my fault from the beginning.

**Comment by larssn** [comment]
There you go 🙂

**Comment by Gustl22** [comment]
Nice big thanks for your contribution!

**Comment by larssn** [comment]
Thanks for helping!

**Review by Gustl22 — APPROVED** [review]

**Review by spydon — APPROVED** [review]

**Comment by larssn** [comment]
@Gustl22 Any idea when this is planned for release? 🙂

**Comment by spydon** [comment]
> @Gustl22 Any idea when this is planned for release? 🙂

As soon as there is a fix in for #1194 we'll definitely do a release, since a lot of people are experiencing that issue. But if there is no fix upcoming for that we can of course do it anyways, it shouldn't be hard to fix that though, but I don't have any Apple devices so I have a hard time testing it.

**Pull request merged**
