### PR TITLE
chore: Make tests less flaky

### PR DESCRIPTION
**Pull request by Gustl22**
- ~Not yet fixed explicitely: TimeoutException for [this](https://github.com/bluefireteam/audioplayers/runs/7283092349?check_suite_focus=true).~ But may not occur anymore due to better performance of emulator. Or if it reoccurs error logging is improved to better estimate the values

### CODE REVIEW

**Review by luanpotter — APPROVED** [review]
LGTM

**Comment by Gustl22** [comment]
It seems like Android emulator on Github Actions needs almost two thirds more computing time, e.g. for calling `pump()` (here almost 1s) which will result in overlooking some frames when testing for a string. Now it only will pump one frame at a time, which hopefully should improve the testing behavior.

**Comment by Gustl22** [comment]
@luanpotter Consider merging #1222 first.

**Comment by spydon** [comment]
> @luanpotter Consider merging #1222 first.

Does this PR need an update after #1222 was merged? (since the android build is failing)

**Comment by Gustl22** [comment]
This is so frustrating. Sorry for the flakiness.
It's likely that another bug occurred which is also likely to be solved in #1238. Even more frustrating is that the previous [test succeded](https://github.com/bluefireteam/audioplayers/runs/7490610314?check_suite_focus=true)
I'm now a bit in a predicament. The tests won't work without the bug fixes and the bug fixes won't work without updating the tests.

**Comment by Gustl22** [comment]
Idk, I thought, by waiting only one frame via `tester.pump()`, the position updates in tests would be more reliably. But it seems like it skipped the first update event none the less. If I test locally all is fine. It's so frustrating to not have the exact same conditions as on the CI machine.

Screenshot from 2022-08-15 18-07-37 
At the moment I have no good idea, how to solve this... :/

**Comment by spydon** [comment]
> This is so frustrating. Sorry for the flakiness. It's likely that another bug occurred which is also likely to be solved in #1238. Even more frustrating is that the previous [test succeded](https://github.com/bluefireteam/audioplayers/runs/7490610314?check_suite_focus=true) I'm now a bit in a predicament. 

Understand your frustration! I wonder if there is any other repository that we can look at how they are handling testing on multiple platforms reliably like this.

> The tests won't work without the bug fixes and the bug fixes won't work without updating the tests.

We can force merge some PR if you think that would help, it's not like it could make it worse from the current testing state. :sweat_smile:

**Comment by spydon** [comment]
Now the tests passed after a restart, do you think it is worth merging this branch and then continue the work in a new PR?
Btw, are you on our discord server? :)
https://discord.com/invite/pxrBmy4

**Comment by Gustl22** [comment]
@spydon I disabled the `onPosition` test on Android for now. It should be safe to merge. We may can think of a better testing strategy for time dependent callback tests, some day... Unfortunately [flutters video_player](https://github.com/flutter/plugins/tree/main/packages/video_player/video_player/example/integration_test) not testing or not even having such callbacks.

**Review by spydon — APPROVED** [review]

**Pull request merged**
