### PR TITLE
fix: Audio not working in iOS 17 for UrlSource

### LINKED ISSUE #1663: Audio not working in iOS 17 for UrlSource
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

After update to **ios 17**, **play()** function fails with following exception. However the same code was **working** fine in **android** as well as **ios 16.**

**[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(DarwinAudioError, Failed to set source. For troubleshooting, see https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md, AVPlayerItem.Status.failed on setSourceUrl, null)**

Any .mp3 file with following code produces the above exception

    AudioPlayer.global.setAudioContext(AudioContextConfig().build());
    final player = AudioPlayer();
    ByteData res = await rootBundle.load('assets/test.mp3');
    await player.play(UrlSource(Uri.dataFromBytes(res.buffer.asUint8List(), mimeType: "audio/mpeg").toString()), volume: 1);

### Expected behaviour

Play the .mp3 file

### Steps to reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

### Code sample

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

iOS

### Platform details

iOS 17

### AudioPlayers Version

5.0.0

### Build mode

debug

### Audio Files/URLs/Sources

_No response_

### Screenshots

_No response_

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Related issues / more information

Problem is with UrlSource. When using asset source on iOS 17, it is working fine.

e.g. -
player.play(AssetSource('test.mp3'));

### Working on PR

no way

### PR DESCRIPTION
**Pull request by andyshephard**
# Description

On iOS17, playing audio data via a UrlSource is broken. This is because Apple have modified the AVPlayer and now expect the AVPlayer instance to be initialised with an AVURLAsset housing the data and making use of the newly-introduced AVURLAssetOverrideMIMETypeKey global variable (https://developer.apple.com/documentation/avfoundation/avurlassetoverridemimetypekey?changes=latest_minor&language=objc)

This PR introduces a fix that initialises the AVPlayer instance using the aforementioned method if the user is attempting to load in a data source. If the user instead uses a URL (http://internet.com/file.mp3), it will use the original approach of initialising AVPlayer with the `url` property.

Original:
```
playerItem = AVPlayerItem(url: parsedUrl)
```

New:
```
let asset = AVURLAsset(url: parsedUrl, options: [AVURLAssetOverrideMIMETypeKey: fileType])
playerItem = AVPlayerItem(asset: asset)
```

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `refactor:`,
      `docs:`, `chore:`, `test:`, `ci:` etc).
- [ ] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation and added dartdoc comments with `///`, where necessary.
- [x] I have updated/added relevant examples in [example].

## Breaking Change

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

## Related Issues

Fixes #1663 

[issue database]: https://github.com/bluefireteam/audioplayers/issues
[Contributor Guide]: https://github.com/bluefireteam/audioplayers/blob/main/contributing.md#feature-requests--prs
[Conventional Commit]: https://conventionalcommits.org
[example]: https://github.com/bluefireteam/audioplayers/tree/main/packages/audioplayers/example

### CODE REVIEW

**Comment by Gustl22** [comment]
This PR may be can connected with #803
and tested by enabling these tests: https://github.com/bluefireteam/audioplayers/blob/87f3cb7e47e2103d2079a3dfe6aebe80c8a76c3d/packages/audioplayers/example/integration_test/lib_test.dart#L82

**Comment by jgrandchavin** [comment]
Hello @andyshephard 

I have tested your code but I still have the same error 😔

```
PlatformException(DarwinAudioError, Failed to set source. For troubleshooting, see https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md, AVPlayerItem.Status.failed on setSourceUrl, null)
```

Here is my code, do you have an idea why it still occurs ?

```
AudioCache? cache;

Future<void> initialize() async {
      if (Platform.isIOS) {
        await AudioPlayer.global.setAudioContext(soundAudioContext);
      }

      cache = AudioCache(prefix: 'res/audio/');
      await Future.wait(Sounds.values.map((sound) async {
        final pool = await AudioPool.createFromAsset(path: sound.fileName, maxPlayers: 5, audioCache: cache);
        _pools.putIfAbsent(sound.name, () => pool);
      }));
  }
```

**Comment by jgrandchavin** [comment]
Finally instead of create every sound pools at launch, I create it when I need it and it fix my issue 👌 Thanks for your code 

```
Future<AudioPool?> _getSoundPool({required Sounds sound}) async {
    try {
      if (!isInitialized) return null;

      if (!_pools.containsKey(sound.name)) {
        final pool = await AudioPool.createFromAsset(
          path: sound.fileName,
          maxPlayers: 3,
          audioCache: cache!,
        );

        _pools.putIfAbsent(sound.name, () => pool);
      }

      return _pools[sound.name];
    } catch (error, trace) {
      log.e('Failed to create sound pool', error, trace);
    }
  }
```

**Comment by jozes** [comment]
Any progress here? I have encountered the same problem on IOS 17, i need to release the app in a very short time so desperately need a fix for IOS 17.

**Pull request closed without merging**
