### PR TITLE
fix: rework dispose

### LINKED ISSUE #1450: Disposed PlayerState
### Use case / Problem

When you dispose an `AudioPlayer` object the `PlayerState` is set to `stopped`. How do you decide now if you want to replay this `AudioPlayer` object or not? if your condition is 

```dart
if (player.state != PlayerState.playing && player.state != PlayerState.completed) {
    player.resume();
}

player.onPlayerComplete.listen((event) {
    circle.player.dispose();
});
```

you are out of luck...

Workaround is to assign `null` to `player` and then check if the player is null....

```dart
player?.onPlayerComplete.listen((event) {
    player?.dispose();
    player = null;
});

if (player != null && player?.state != PlayerState.playing && player?.state != PlayerState.completed) {
    player?.dispose();
    player = null;
}
```

### Proposal / Solution

Add `PlayerSate.disposed`

### Example Code

```dart
if (player.state != PlayerState.disposed && player.state != PlayerState.playing && player.state != PlayerState.completed) {
    player.resume();
}
```

### LINKED ISSUE #1475: `Expression: cannot dereference end map/set iterator` on Windows
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

Audio cannot be played on Windows due to a MVC++ error occuring.

### Expected behaviour

Audio should play without any problem.

### Steps to reproduce

1. Clone the repository and extract the `flame_audio` example project.
2. Run `flutter create .` in order to create the Windows project.
3. `flutter run`.

### Code sample

<details>
<summary>Code sample</summary>

```dart
import 'package:flame/components.dart';
import 'package:flame/extensions.dart';
import 'package:flame/game.dart';
import 'package:flame/input.dart';
import 'package:flame/palette.dart';
import 'package:flame_audio/flame_audio.dart';
import 'package:flutter/widgets.dart' hide Animation;

void main() {
  runApp(GameWidget(game: AudioGame()));
}

/// This example game showcases three possible use cases:
///
/// 1. Use the static FlameAudio class to easily fire a sfx using the default
/// configs for the button tap.
/// 2. Uses a custom AudioPool for extremely efficient audio loading and pooling
/// for tapping elsewhere.
/// 3. Uses the Bgm utility for background music.
class AudioGame extends FlameGame with TapDetector {
  static Paint black = BasicPalette.black.paint();
  static Paint gray = const PaletteEntry(Color(0xFFCCCCCC)).paint();
  static TextPaint text = TextPaint(
    style: TextStyle(color: BasicPalette.white.color),
  );

  late AudioPool pool;

  @override
  Future<void> onLoad() async {
    pool = await FlameAudio.createPool(
      'sfx/fire_2.mp3',
      minPlayers: 3,
      maxPlayers: 4,
    );
    startBgmMusic();
  }

  Rect get button => Rect.fromLTWH(20, size.y - 300, size.x - 40, 200);

  void startBgmMusic() {
    FlameAudio.bgm.initialize();
    FlameAudio.bgm.play('music/bg_music.ogg');
  }

  void fireOne() {
    FlameAudio.play('sfx/fire_1.mp3');
  }

  void fireTwo() {
    pool.start();
  }

  @override
  void render(Canvas canvas) {
    super.render(canvas);
    canvas.drawRect(size.toRect(), black);

    text.render(
      canvas,
      '(click anywhere for 1)',
      Vector2(size.x / 2, 200),
      anchor: Anchor.topCenter,
    );

    canvas.drawRect(button, gray);

    text.render(
      canvas,
      'click here for 2',
      Vector2(size.x / 2, size.y - 200),
      anchor: Anchor.bottomCenter,
    );
  }

  @override
  void onTapDown(TapDownInfo info) {
    if (button.containsPoint(info.eventPosition.game)) {
      fireTwo();
    } else {
      fireOne();
    }
  }
}
```

</details>

(as you can see, it's the sample project of `flame_audio`, which is available [here](https://github.com/flame-engine/flame/tree/main/packages/flame_audio/example)).

### Affected platforms

Windows

### Platform details

**Processor :** AMD Ryzen 5 5600H with Radeon Graphics            3.30 GHz
**RAM :**	16,0 Go (15,3 Go usable)
**Edition :**	Windows 11 Famille
**Version :**	22H2
**Installed on :** ‎05/‎10/‎2022
**OS Build :**	22621.1555
**Experience :**	Windows Feature Experience Pack 1000.22640.1000.0

### AudioPlayers Version

4.0.1

### Build mode

debug

### Audio Files/URLs/Sources

[`bg_music.ogg`](https://github.com/flame-engine/flame/blob/main/packages/flame_audio/example/assets/audio/music/bg_music.ogg)

### Logs

No log as it's a native error. See screenshot above.

### Related issues / more information

_No response_

### Working on PR

Why not, but I have no C++ experience.

### LINKED ISSUE #1478: AudioPool dispose() method
### Checklist

- [X] I made sure that the issue I am raising doesn't already exist

### Use case / Problem

The `AudioPool` class does not have a `dispose` method.

### Proposal / Solution

It seems that you need to call the `dispose` method on each thread, synchronizing with the `_lock` field.

### Example Code

_No response_

### Affected platforms

Linux

### Platform details

In Linux, this leads to an uncontrolled multiplication of playback streams.

### Audio Files/URLs/Sources

_No response_

### Mockups

_No response_

### Related issues / more information

_No response_

### Working on PR

yeah

### LINKED ISSUE #1481: Methods marked with @UiThread must be executed on the main thread.
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

```
E/flutter (30453): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(AndroidAudioError, Methods marked with @UiThread must be executed on the main thread. Current thread: DefaultDispatcher-worker-2, java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: DefaultDispatcher-worker-2
E/flutter (30453): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:1415)
E/flutter (30453): 	at io.flutter.embedding.engine.FlutterJNI.dispatchEmptyPlatformMessage(FlutterJNI.java:1015)
E/flutter (30453): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:280)
E/flutter (30453): 	at io.flutter.embedding.engine.dart.DartExecutor$DefaultBinaryMessenger.send(DartExecutor.java:452)
E/flutter (30453): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:212)
E/flutter (30453): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.endOfStream(EventChannel.java:270)
E/flutter (30453): 	at xyz.luan.audioplayers.EventHandler.endOfStream(AudioplayersPlugin.kt:354)
E/flutter (30453): 	at xyz.luan.audioplayers.player.WrappedPlayer.dispose(WrappedPlayer.kt:356)
E/flutter (30453): 	at xyz.luan.audioplayers.AudioplayersPlugin.handler(AudioplayersPlugin.kt:197)
E/flutter (30453): 	at xyz.luan.audioplayers.AudioplayersPlugin.access$handler(AudioplayersPlugin.kt:29)
E/flutter (30453): 	at xyz.luan.audioplayers.AudioplayersPlugin$onAttachedToEngine$1$1.invoke(AudioplayersPlugin.kt:50)
E/flutter (30453): 	at xyz.luan.audioplayers.AudioplayersPlugin$onAttachedToEngine$1$1.invoke(AudioplayersPlugin.kt:50)
E/flutter (30453): 	at xyz.luan.audioplayers.AudioplayersPlugin$safeCall$1.invokeSuspend(AudioplayersPlugin.kt:74)
E/flutter (30453): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/flutter (30453): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/flutter (30453): 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
E/flutter (30453): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
E/flutter (30453): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
E/flutter (30453): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
E/flutter (30453): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
E/flutter (30453): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
E/flutter (30453): , null)
E/flutter (30453): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
E/flutter (30453): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
E/flutter (30453): <asynchronous suspension>
E/flutter (30453): #2      AudioPlayer.dispose (package:audioplayers/src/audioplayer.dart:353:5)
E/flutter (30453): <asynchronous suspension>
E/flutter (30453): 
```

### Expected behaviour

No exception

### Steps to reproduce

_No response_

### Code sample

<details>
<summary>Code sample</summary>

```dart
// any Stateful widget

  late final AudioPlayer _audioPlayer;

  @override
  void initState() {
    _audioPlayer = AudioPlayer(playerId: widget.url)
      ..setReleaseMode(ReleaseMode.stop);
    // subscribing to some events skipped but it does not matter
    super.initState();
  }

  @override
  void dispose() {
    _durationSubscription?.cancel();
    _positionSubscription?.cancel();
    _playerCompleteSubscription?.cancel();
    _playerStateChangeSubscription?.cancel();
    _audioPlayer.dispose();
    super.dispose();
  }

```

</details>

### Affected platforms

Android

### Platform details

Android 13 Xaomi 12T Pro

### AudioPlayers Version

pub.dev 4.0.1

### Build mode

debug

### Audio Files/URLs/Sources

any

### Screenshots

_No response_

### Logs

```
[√] Flutter (Channel stable, 3.7.12, on Microsoft Windows [Version 10.0.22621.1555], locale ru-RU)
    • Flutter version 3.7.12 on channel stable at c:\Soft\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (4 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at c:\Soft\AndroidSDK
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Soft\AndroidStudio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\...\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.8.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.8.30907.101
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Soft\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] Connected device (4 available)
    • 22081212UG (mobile) • 90e348c8 • android-arm64  • Android 13 (API 33)
    • Windows (desktop)   • windows  • windows-x64    • Microsoft Windows [Version 10.0.22621.1555]
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 111.0.5563.149
    • Edge (web)          • edge     • web-javascript • Microsoft Edge 112.0.1722.48

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

### Related issues / more information

_No response_

### Working on PR

no way

### PR DESCRIPTION
**Pull request by Gustl22**
# Description

- Add `PlayerState.disposed` (closes #1450)
- Add `AudioPool.dispose()` (closes #1478)
- Dispose players in tests
- Properly handle dispose on all platforms (closes #1475)
- Fix running method calls on non UI threads causes PlatformException (closes #1481)

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:`, `chore:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation and added dartdoc comments with `///`, where necessary.
- [x] I have updated/added relevant examples in [example].

## Breaking Change

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

## Related Issues

Closes #1450 
Closes #1478 
Closes #1475 
Closes #1481

### CODE REVIEW

**Comment by putnokiabel** [comment]
Any idea when the next release that includes this fix might be?

**Comment by Gustl22** [comment]
I probably need to fix the pipeline first, and support Android AGP 8. Hopefully soon, but can't give any promises.

**Comment by putnokiabel** [comment]
Is there a way to manually use the version on `main` until then (I'm running into this issue in production and would like to use the fix as soon as I'm able to)?

I've tried using `audioplayers` as a git dependency (as opposed to fetching from pub dev), but it seems that it depends on the versions of `audioplayers_android`, `audioplayers_darwin` etc. that are published (and therefore aren't compatible).

**Comment by Gustl22** [comment]
Add to your `pubspec.yaml`:
```
dependency_overrides:
  audioplayers:
    git:
      url: https://github.com/bluefireteam/audioplayers.git
      path: 'packages/audioplayers'
  audioplayers_platform_interface:
    git:
      url: https://github.com/bluefireteam/audioplayers.git
      path: 'packages/audioplayers_platform_interface'
  audioplayers_web:
    git:
      url: https://github.com/bluefireteam/audioplayers.git
      path: 'packages/audioplayers_web'
  audioplayers_linux:
    git:
      url: https://github.com/bluefireteam/audioplayers.git
      path: 'packages/audioplayers_linux'
  audioplayers_android:
    git:
      url: https://github.com/bluefireteam/audioplayers.git
      path: 'packages/audioplayers_android'
  audioplayers_darwin:
    git:
      url: https://github.com/bluefireteam/audioplayers.git
      path: 'packages/audioplayers_darwin'
  audioplayers_windows:
    git:
      url: https://github.com/bluefireteam/audioplayers.git
      path: 'packages/audioplayers_windows'
```

**Comment by putnokiabel** [comment]
Thank you so much, that helps a lot! 🙏

**Comment by fzyzcjy** [comment]
Looking forward to the fix!

**Comment by fzyzcjy** [comment]
@Gustl22 Hi, I wonder which commit will be the stable one (to be published)? I want to use it in production, so I hope not to use the unstable master branch.

**Comment by Gustl22** [comment]
We don't really differentiate `main` and `stable`. We always try to keep the library free from bugs with help of tests. We don't have the customers and the resources to provide multiple channels. The most stable is the last minor version before a major update I guess, but the last commit on `main` tackles the most bugs. So it's your choice what you consider as the most appropriate for you.
We make a release, when we think all major issues are resolved by then.

**Comment by adigujjar** [comment]
@Gustl22 
Whenever i try to run ios build on simulator i got this
@import audioplayers_darwin;
Module 
audioplayers_darwin not found

**Comment by Gustl22** [comment]
@adigujjar Plz try out the example and work out the differences:
https://github.com/bluefireteam/audioplayers/tree/main/packages/audioplayers/example

**Pull request merged**
