### PR TITLE
fix(android): Avoid ConcurrentModificationException

### LINKED ISSUE #1274: Crash on Android Error: java.util.ConcurrentModificationException
## Checklist
- [x] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [x] I made sure that the issue I am raising doesn't already exist

## Current bug behaviour

App crahses when user press many buttons at once in Xylophone app.

## Expected behaviour

I made a Xylophone App on flutter. You can click different buttons and it play different audios. But when use press many buttons in fast speed this app crashes and show this error. I only tested this app on Android.

## Steps to reproduce

```
void playNote(int noteNumber){
    final player = AudioPlayer();
    player.play(AssetSource('note$noteNumber.wav'));
  }
```

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

## Logs

```
E/AndroidRuntime( 6063): java.util.ConcurrentModificationException
E/AndroidRuntime( 6063): 	at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:411)
E/AndroidRuntime( 6063): 	at java.util.LinkedHashMap$ValueIterator.next(LinkedHashMap.java:426)
E/AndroidRuntime( 6063): 	at xyz.luan.audioplayers.AudioplayersPlugin$UpdateCallback.run(AudioplayersPlugin.kt:208)
E/AndroidRuntime( 6063): 	at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime( 6063): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 6063): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime( 6063): 	at android.app.ActivityThread.main(ActivityThread.java:6077)
E/AndroidRuntime( 6063): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6063): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
E/AndroidRuntime( 6063): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

## Audio Files/URLs/Sources

- Audio Files : https://drive.google.com/drive/folders/1Hf5sWMtroSgYJGV3NSlLQCwO6Q0EDbES?usp=sharing

## Environment information

* audioplayers version: 1.0.1

Platform 1: 
* OS name and version:  Android 9 (Physical), Android 6 (Emulator)
* Device: Mobile

* build mode: `debug`

* error peculiarities (optional): 

Platforms tested without any issue (optional): 
* test peculiarities:

### PR DESCRIPTION
**Pull request by spydon**
# Description

When playing a lot of sounds simultaneously apparently some users get `ConcurrentModificationException` in this for loop.
The best solution would be to be able to use a `ConcurrentHashMap`, but I don't know how to do that in here.

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:`, `chore:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation and added dartdoc comments with `///`, where necessary.
- [x] I have updated/added relevant examples in [example].

## Breaking Change

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

## Related Issues

Closes #1274 

[issue database]: https://github.com/bluefireteam/audioplayers/issues
[Contributor Guide]: https://github.com/bluefireteam/audioplayers/blob/main/contributing.md#feature-requests--prs
[Conventional Commit]: https://conventionalcommits.org
[example]: https://github.com/bluefireteam/audioplayers/tree/main/packages/audioplayers/example

### CODE REVIEW

**Comment by Gustl22** [comment]
I'll have a look later this week :)

**Comment by spydon** [comment]
> I'll have a look later this week :)

None of my tried worked so not much to have a look at yet 😅

**Comment by Gustl22** [comment]
@spydon I reproduced the issue reliably and with the `ConcurrentMap` it was fixed. Only the declaration was missing :)

**Review by Gustl22 — APPROVED** [review]

**Comment by spydon** [comment]
> @spydon I reproduced the issue reliably and with the `ConcurrentMap` it was fixed. Only the declaration was missing :)

That's awesome to hear!

**Pull request merged**
