### PR TITLE
chore(release): publish packages

### PR DESCRIPTION
**Pull request by spydon**
- audioplayers@2.0.0
 - audioplayers_darwin@2.0.0
 - audioplayers_platform_interface@3.0.0
 - audioplayers_android@1.1.4
 - audioplayers_windows@1.1.2
 - audioplayers_linux@1.0.3
 - audioplayers_web@2.1.1

### CODE REVIEW

**Comment by Gustl22** [comment]
I honestly couldn't test the change of #1374 on my emulator because I'm traveling right now, it was all a theoretical thing. I totally rely on the CI (which does not check the actual sound output) or other developers 😅

**Comment by Gustl22** [comment]
@lukepighetti @OlegNovosad can you do us a favor and test this before release?

```
dependency_overrides:
  audioplayers:
    git:
      url: https://github.com/bluefireteam/audioplayers.git
      path: 'packages/audioplayers'
      ref: '1499a51037e900b7a41ef3514803db8472ed767f'
  audioplayers_platform_interface:
    git:
      url: https://github.com/bluefireteam/audioplayers.git
      path: 'packages/audioplayers_platform_interface'
      ref: '1499a51037e900b7a41ef3514803db8472ed767f'
  audioplayers_darwin:
    git:
      url: https://github.com/bluefireteam/audioplayers.git
      path: 'packages/audioplayers_darwin'
      ref: '1499a51037e900b7a41ef3514803db8472ed767f'
```

Would be a great help!

**Comment by spydon** [comment]
> I honestly couldn't test the change of #1374 on my emulator because I'm traveling right now, it was all a theoretical thing. I totally rely on the CI (which does not check the actual sound output) or other developers 😅

It should™️  be the same as the change they tried on the issue, so I'm pretty confident that it will work. 😄

**Review by luanpotter — APPROVED** [review]
:shipit:

**Pull request merged**
