### PR TITLE
fix(android): `onPlayerStateChanged` is not called when audio has completed playing

### LINKED ISSUE #1522: (with PR) `onPlayerStateChanged` is not called when audio has completed playing
## Bug description

`onPlayerStateChanged` does not emit `completed` event when audio has completed playing.

## Cause analysis

After logging, I realize it is because of the following timing:

1. Android MediaPlayer has completed playing. It calls the callback set in MediaPlayerPlayer, and thus call `wrappedPlayer.onCompletion`. Thus, `AudioplayersPlugin.handleComplete` is called. It executes `handler.post { player.eventHandler.success("audio.onComplete") }`.
3. Just immediately after that, `AudioplayersPlugin.stopUpdates` is called. This is probably caused by `UpdateRunnable.run`.

Let's analyze it: Just after `handler.post` and before the `player.eventHandler.success` has a chance to be executed, `stopUpdates` is called, thus `handler.removeCallbacksAndMessages`, and thus `player.eventHandler.success` is never called, so I cannot receive the `completed` event!

### PR DESCRIPTION
**Pull request by fzyzcjy**
# Description

Close #1522 

I am not sure whether this is the best way, but I can confirm it fixes the bug I see, and IMHO there are not infinitely many handler callbacks, so skipping this cancelation does not cause harm.

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:`, `chore:` etc).
- [ ] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.
- [ ] I have updated/added relevant documentation and added dartdoc comments with `///`, where necessary.
- [ ] I have updated/added relevant examples in [example].

## Breaking Change

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

## Related Issues

[issue database]: https://github.com/bluefireteam/audioplayers/issues
[Contributor Guide]: https://github.com/bluefireteam/audioplayers/blob/main/contributing.md#feature-requests--prs
[Conventional Commit]: https://conventionalcommits.org
[example]: https://github.com/bluefireteam/audioplayers/tree/main/packages/audioplayers/example

### CODE REVIEW

**Comment by Gustl22** [comment]
Nice catch!

Do you think `updateRunnable?.let { handler.removeCallbacks(it) }` would do the trick?

But I'm a bit confused about the comment below [this](https://stackoverflow.com/a/33469423/5164462), but it should't make a big difference, as the runnable (and it's loop) will end after one update event. We may should test this once anyway :)

**Comment by fzyzcjy** [comment]
> Do you think updateRunnable?.let { handler.removeCallbacks(it) } would do the trick?

I am not sure. If it only removes that one specific runnable then maybe yes?

**Comment by fzyzcjy** [comment]
Btw this is partially why I do hope to implement https://github.com/bluefireteam/audioplayers/issues/1527 - then there is no such callbacks, runnables, threads, etc!

**Review by Gustl22 — APPROVED** [review]

**Comment by Gustl22** [comment]
@fzyzcjy Is it ok for you to merge it like this (after my changes)?

**Comment by fzyzcjy** [comment]
LGTM!

**Pull request merged**
