### PR TITLE
Added setBalance method

### PR DESCRIPTION
**Pull request by novikov-studio**
# Description

Added method:
```
/// -1 - The left channel is at full volume; the right channel is silent.
///  1 - The right channel is at full volume; the left channel is silent.
///  0 - Both channels are at the same volume.
AudioPlayer.setBalance(double value)
```

## Related Issues
#58

### CODE REVIEW

**Comment by spydon** [comment]
How come this PR was closed? Seems like a useful feature :)

**Comment by novikov-studio** [comment]
@spydon, it leaks from my sandbox :) Now I'm ready [here](https://github.com/novikov-studio/audioplayers/pull/1). Should I need create a new PR?

**Comment by spydon** [comment]
> @spydon, it leaks from my sandbox :) Now I'm ready [here](https://github.com/novikov-studio/audioplayers/pull/1). Should I need create a new PR?

Sure, that would be nice! Either update this PR or add a new one, whatever is the most convenient for you.

**Comment by novikov-studio** [comment]
new PR #1248

**Pull request closed without merging**
