### PR TITLE
test: Attempt to fix flaky tests for Windows & Android

### PR DESCRIPTION
**Pull request by Gustl22**
# Description

The tests in Windows & Android are possibly flaky for this reason:
- In general it is not tested, if a source starts to play for app tests.
- In the app test for `ReleaseMode.loop`, the source starts to play, but never completes or stops. See: https://github.com/bluefireteam/audioplayers/blob/fe81f3b1e600fe005febbe7cd3da02735a3de004/packages/audioplayers/example/integration_test/app/tabs/controls_tab.dart#L104 . This is now checked by getting the current position.

The solution to the problem also raises another issue on Android, as the position can not be retrieved on very short sources, thus they are excluded from these tests and it is expected to make it work with Exoplayer (#1526).

~Sometimes CI fails, cause Windows needs a long time to finish playing a source with lengths `< 2s`. 
See: https://github.com/bluefireteam/audioplayers/actions/runs/4455910532/jobs/7826010863
This increases the timeout, so `onComplete` should be called in that time slot.~

- [x] also need to resolve flaky event stream test in [current master](https://github.com/bluefireteam/audioplayers/actions/runs/4607358340/jobs/8141777821). Probably because test finishes before having expected all values: https://github.com/bluefireteam/audioplayers/blob/8babb0e57d4e2d1834f99b3a949438e4f9a141d8/packages/audioplayers/test/audioplayers_test.dart#L125

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:`, `chore:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation and added dartdoc comments with `///`, where necessary.
- [ ] I have updated/added relevant examples in [example].

## Breaking Change

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

## Related Issues

https://github.com/bluefireteam/audioplayers/actions/workflows/test.yml?query=branch%3Agustl22%2Fincrease-timeout-windows

### CODE REVIEW

**Comment by Gustl22** [comment]
How debugging this feels like:
image

**Comment by Gustl22** [comment]
This only happens if GH is on its limits and takes longer than expected for some tasks... 😪 Very flaky, but hope to fix it some day.

**Comment by Gustl22** [comment]
Maybe due to: https://github.com/actions/runner-images/issues/7320

**Comment by Gustl22** [comment]
Still a problem because same [failure](https://github.com/bluefireteam/audioplayers/actions/runs/5082397624/jobs/9132074162) was caused after fixing windows with https://github.com/bluefireteam/audioplayers/pull/1441/commits/028e2d29365ba11e0cbecd06303e96df0c9d77cc

**Review by spydon — APPROVED** [review]

**Comment by Gustl22** [comment]
Still not fixed according to https://github.com/bluefireteam/audioplayers/actions/runs/6110536581/job/16584118505
But let's see how many times this occurs.

**Pull request merged**
