### PR TITLE
fix!: Change the default value of iOS audio context to force speakers

### PR DESCRIPTION
**Pull request by luanpotter**
# Description

There has been a high number of issues being opened around the fact that on 1.0.0, `forceSpeaker` on iOS (and android) was set to `false` by default, requiring most users to explicitly setup the global audio context.

This change the default value of iOS audio context to force speakers to be inline with what users seem to expect.

Follow [this thread](https://github.com/bluefireteam/audioplayers/issues/1194) for details.

Since I only test iOS on emulators, where this setting doesn't make any difference, I hadn't realized this issue.

Note: this changes the default for android as well, which is in line with the unified audio context philosophy.

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:`, `chore:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation and added dartdoc comments with `///`, where necessary.
- [x] I have updated/added relevant examples in [example].

## Breaking Change

- [x] Yes, this is a breaking change.
- [ ] No, this is *not* a breaking change.

### Migration instructions

If you wanted to have it set to false, you can just set it so:

```dart
      final AudioContext audioContext = AudioContext(
        iOS: AudioContextIOS(
          defaultToSpeaker: false,
         // ...
        ),
        // ...
      );
      AudioPlayer.global.setGlobalAudioContext(audioContext);
```

If not, you can remove all the ad-hoc code you had to set this up.

## Related Issues

[issue database]: https://github.com/bluefireteam/audioplayers/issues
[Contributor Guide]: https://github.com/bluefireteam/audioplayers/blob/main/contributing.md#feature-requests--prs
[Conventional Commit]: https://conventionalcommits.org
[example]: https://github.com/bluefireteam/audioplayers/tree/main/packages/audioplayers/example

### CODE REVIEW

**Comment by luanpotter** [comment]
Tested on iOS emulator, seem to be working just as before.

**Comment by spydon** [comment]
Woooop woop! 🍻😍

**Review by spydon — APPROVED** [review]

**Comment by Gustl22** [comment]
Do we have any possibility to test this on a real device @luanpotter?
We may could ask in the thread, to test this branch(?).
Or we just try out the change and see if anyone complains after the release?

**Comment by spydon** [comment]
> Do we have any possibility to test this on a real device @luanpotter? 

He doesn't.

> We may could ask in the thread, to test this branch(?). I for myself managed to get it running on a real ipad compliling via MacOS VM. But that doesn't have an Earpeace, so there's no difference noticable in changing the settings. Or we just try out the change and see if anyone complains after the release?

I'll do a release and tell people in the thread to try, we can just roll it back and do a new release if some iPhone's explode. 😅

**Pull request merged**
