### PR TITLE
chore(workflows): customizable workflows

### PR DESCRIPTION
**Pull request by Gustl22**
# Description

* ability to trigger each job individually via workflow_dispatch
* categorize reusable workflows / jobs into `build` and `test`
* split trigger into `pull-request` and `release`

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:`, `chore:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation and added dartdoc comments with `///`, where necessary.
- [x] I have updated/added relevant examples in [example].

## Breaking Change

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

## Related Issues
#1333

[issue database]: https://github.com/bluefireteam/audioplayers/issues
[Contributor Guide]: https://github.com/bluefireteam/audioplayers/blob/main/contributing.md#feature-requests--prs
[Conventional Commit]: https://conventionalcommits.org
[example]: https://github.com/bluefireteam/audioplayers/tree/main/packages/audioplayers/example

### CODE REVIEW

**Comment by Gustl22** [comment]
For this to work correctly we have to change protection rules to allow merging, when `pull_request` workflow passed, and not anymore the `build` workflow.
https://github.com/orgs/community/discussions/26698#discussioncomment-3252954
`build` and `test` are reusable now, and can be called by its trigger workflow `pull_request` or `release`, which makes more sense in terms of naming.

**Comment by luanpotter** [comment]
@Gustl22 done!

**Review by luanpotter — APPROVED** [review]
LGTM

**Comment by Gustl22** [comment]
Thank you!!

**Pull request merged**
