### PR TITLE
uncatch exception will cause app crash

### PR DESCRIPTION
**Pull request by keengo99**
fix stop & release uncatch exception will cause app crash

### CODE REVIEW

**Comment by Gustl22** [comment]
@keengo99 I think it would be better to fix the cause of the exception instead of catching everything... What exception are we talking about?

**Review by luanpotter — CHANGES_REQUESTED** [review]
Agreed, this will just silence all the errors!

**Comment by keengo99** [comment]
I already use try catch in dart code.
but it dosen't work.
```
try {
     if (_player != null) {
          await _player!.dispose();
          _player = null;
     }
   ...
} catch (e, stackTrace) {
      _playError(e, stackTrace);
    }
```

**Comment by Gustl22** [comment]
But what is the actual error message, when the App crashes, without any catches? We need to figure out the cause, to validate and reproduce it. Do you have a working code example, which can reproduce the behavior?

**Comment by keengo99** [comment]
```
D/MediaPlayerNative(21972): Message: MEDIA_ERROR(100), ext1=Unknown MediaErrorType(-38), ext2=0x0
V/PlayerBase(21972): baseRelease() piid=7215 state=4
D/MediaPlayerNative(21972): Message: Unknown MediaEventType(8), ext1=0, ext2=0x0
E/MediaPlayerNative(21972): error (-38, 0)
I/MediaPlayer(21972): [HSM] stayAwake false uid: 10353, pid: 21972
V/PlayerBase(21972): baseStop() piid=7215
V/MediaPlayer(21972): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(21972): cleanDrmObj: mDrmObj=null mDrmSessionId=null
I/MediaPlayerNative(21972): Pid:21972 MediaPlayer destructor MediaPlayer(0x7d3dfd7c80)
I/MediaPlayer(21972): [HSM] stayAwake false uid: 10353, pid: 21972
I/BlockMonitor(21972): dispatchingThrewException In MainThread
D/AndroidRuntime(21972): Shutting down VM
I/QarthLog(21972): [PatchStore] createDisableExceptionQarthFile
I/QarthLog(21972): [PatchStore] create disable file for com.example.music uid is 10353
E/AndroidRuntime(21972): FATAL EXCEPTION: main
E/AndroidRuntime(21972): Process: com.example.music, PID: 21972
E/AndroidRuntime(21972): java.lang.IllegalStateException
E/AndroidRuntime(21972): 	at android.media.MediaPlayer._reset(Native Method)
E/AndroidRuntime(21972): 	at android.media.MediaPlayer.reset(MediaPlayer.java:2358)
E/AndroidRuntime(21972): 	at xyz.luan.audioplayers.player.MediaPlayerPlayer.release(MediaPlayerPlayer.kt:71)
E/AndroidRuntime(21972): 	at xyz.luan.audioplayers.player.WrappedPlayer.release(WrappedPlayer.kt:198)
E/AndroidRuntime(21972): 	at xyz.luan.audioplayers.player.WrappedPlayer.stop(WrappedPlayer.kt:186)
E/AndroidRuntime(21972): 	at xyz.luan.audioplayers.player.WrappedPlayer.onCompletion(WrappedPlayer.kt:240)
E/AndroidRuntime(21972): 	at xyz.luan.audioplayers.player.MediaPlayerPlayer.createMediaPlayer$lambda-5$lambda-1(MediaPlayerPlayer.kt:18)
E/AndroidRuntime(21972): 	at xyz.luan.audioplayers.player.MediaPlayerPlayer.lambda$3fK1i48Yert5dbg2Q8ZiB5tiKHg(Unknown Source:0)
E/AndroidRuntime(21972): 	at xyz.luan.audioplayers.player.-$$Lambda$MediaPlayerPlayer$3fK1i48Yert5dbg2Q8ZiB5tiKHg.onCompletion(Unknown Source:2)
E/AndroidRuntime(21972): 	at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:3677)
E/AndroidRuntime(21972): 	at android.os.Handler.dispatchMessage(Handler.java:110)
E/AndroidRuntime(21972): 	at android.os.Looper.loop(Looper.java:219)
E/AndroidRuntime(21972): 	at android.app.ActivityThread.main(ActivityThread.java:8668)
E/AndroidRuntime(21972): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21972): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime(21972): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
I/Process (21972): Sending signal. PID: 21972 SIG: 9
Lost connection to device.
Exited (sigterm)
```

**Pull request closed without merging**
