### PR TITLE
chore: support flutter 3.3.0

### PR DESCRIPTION
**Pull request by Gustl22**
- fix linting
- switch to stable channel for web

Also necessary to fix CI, which fails on flutter analyze.

# Description

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:`, `chore:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation and added dartdoc comments with `///`, where necessary.
- [x] I have updated/added relevant examples in [example].

## Breaking Change

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

## Related Issues

[issue database]: https://github.com/bluefireteam/audioplayers/issues
[Contributor Guide]: https://github.com/bluefireteam/audioplayers/blob/main/contributing.md#feature-requests--prs
[Conventional Commit]: https://conventionalcommits.org
[example]: https://github.com/bluefireteam/audioplayers/tree/main/packages/audioplayers/example

### CODE REVIEW

**Review by spydon — APPROVED** [review]

**Comment by spydon** [comment]
Doesn't the pubspec also have to be changed?

**Comment by Gustl22** [comment]
I think project only needs a min flutter version.
```
environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"
```
No need to specify the exact version ;D

**Comment by spydon** [comment]
> I think project only needs a min flutter version.
> ```
> environment:
>   sdk: ">=2.14.0 <3.0.0"
>   flutter: ">=2.5.0"
> ```
> No need to specify the exact version ;D

But won't the analyzer complain if running this with an old flutter version?

**Comment by Gustl22** [comment]
I see. I did some research and found the according MR: https://github.com/flutter/flutter/pull/104231
If you search for `import 'dart:typed_data'` in the _flutter/plugins_ repository, you get some results like this for [camera](https://github.com/flutter/plugins/blob/main/packages/camera/camera_avfoundation/test/type_conversion_test.dart).
They simply ignore the lint error with `// ignore: unnecessary_import`, but also saying to remove it, when the according flutter release is stable, but they didn't remove it yet.
Is it too intrusive to force updating flutter to `3.3.0` immediately or should we ignore the linting for these cases for now?

**Comment by spydon** [comment]
I think it's better to use the ignore for now and upgrade everything at once (the Dart version is also on an old version).

**Review by spydon — APPROVED** [review]
Good that you put in the TODOs 👍

**Pull request merged**
