### PR TITLE
fix: Audio not working in iOS 17 for UrlSource

### PR DESCRIPTION
**Pull request by samdeane**
This is a re-tread of @andyshephard's PR https://github.com/bluefireteam/audioplayers/pull/1728#issue-2037815778.

It looks like the tests are failing on that one (maybe just because linting is failing?), so I've recreated it in a place where I can potentially fix it.

### CODE REVIEW

**Comment by samdeane** [comment]
I can take a look, but I don't have a lot of time to spend on it, unfortunately. 

Do you know what is failing on your #1763 branch? It looks like the iOS tests are failing along with the macOS 14 ones?

**Comment by Gustl22** [comment]
The thing is I tried to make data uris work on ios 16 and 17. And there I need two different sets of options and xcode for ios 16 the option for ios 17 is not recognized, although it is wrapped within `#available` see:
```
Swift Compiler Error (Xcode): Cannot find 'AVURLAssetOverrideMIMETypeKey' in scope 

/Users/runner/work/audioplayers/audioplayers/packages/audioplayers_darwin/darwin/Classes/WrappedMediaPlayer.swift:184:36
```

And macOS 14 is succesding in the tesrs regardless of my changes.

I guess we have to rebuild the ios/macos folder with the new flutter version and do a pod install to work properly. (Just a guess)

**Comment by samdeane** [comment]
This is likely to be the problem on mac-os. The tests are throwing up a system dialogue and will hang until it goes away.

image

Need to take a look at the code signing options to see why that dialogue is appearing.

**Comment by samdeane** [comment]
There's a difference between testing for iOS 16 and building with an old version of XCode that only knows about iOS 16.

To use the code wrapped in `#available` you still have to be building against a version of the SDK that knows about that version - which means using a Github Actions mac runner with Xcode 15.

**Comment by samdeane** [comment]
It looks like the GH actions macos-13 image has Xcode 15 installed, and also has both the iOS 16 and ios 17 SDKs, so using that should be sufficient:

**Comment by Gustl22** [comment]
Thank you for your help and the detailed answers!

> This is likely to be the problem on mac-os. The tests are throwing up a system dialogue and will hang until it goes away.

The thing is, it passes several tests, but not the others. So this is unlikely to be a signing problem, I think:
https://github.com/bluefireteam/audioplayers/actions/runs/8293438418/job/22696520861?pr=1769

> To use the code wrapped in #available you still have to be building against a version of the SDK that knows about that version - which means using a Github Actions mac runner with Xcode 15.

Yeah that's what I thought, too.

> It looks like the GH actions macos-13 image has Xcode 15 installed, and also has both the iOS 16 and ios 17 SDKs, so using that should be sufficient

But it seems, that I have to build with xcode 15, and then somehow run on XCode 14 in order to get the required iOS version 16. 16 is not available on XCode 15 (macOS 13).

> You could instead use simctl to create test devices with specific device/sdk combinations, and then run the tests on each on in turn.

Thank you :) That's what I actually tried here, but fails, because ios 16 is not available in that XCode version. 
https://github.com/bluefireteam/audioplayers/pull/1763/commits/1471576c0a017f1d5721099d0a26dff4cd812377

**Comment by samdeane** [comment]
> But it seems, that I have to build with xcode 15, and then somehow run on XCode 14 in order to get the required iOS version 16. 16 is not available on XCode 15 (macOS 13).

16 is not available by default on Xcode 15, but it is installable. That GH page I linked to implied that a number of SDKs are installed on the macos-13 image, including both the 16 and 17 ones. If I get time I can try a few experiments but you should be able to install and run with the iOS 16 SDK on Xcode 15.

**Comment by Gustl22** [comment]
Ok thanks for your help. I appreciate it. I try to get it working ;D

**Comment by samdeane** [comment]
If I get some time, I will experiment and let you know what I come up with.

**Comment by Gustl22** [comment]
I finally got ios 16 working, by switching with `sudo xcode-select -switch /Applications/Xcode_14.3.1.app/Contents/Developer`.

**Comment by Gustl22** [comment]
This should be covered in #1763, the tests are tried to be fixed in #1769, I appreciate any help though.

**Pull request closed without merging**
