### PR TITLE
fix(web): Avoid stutter when starting playback

### PR DESCRIPTION
**Pull request by blaugold**
# Description

Setting `currentTime` of `AudioElement` after calling `play` can cause a stutter, if the browser is able to start playback of the audio immediately and execution after `play` is delayed by other tasks in the event loop.

By setting `currentTime` before calling `play` this issue can be avoided.

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:`, `chore:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation and added dartdoc comments with `///`, where necessary.
- [x] I have updated/added relevant examples in [example].

## Breaking Change

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

## Related Issues

[issue database]: https://github.com/bluefireteam/audioplayers/issues
[Contributor Guide]: https://github.com/bluefireteam/audioplayers/blob/main/contributing.md#feature-requests--prs
[Conventional Commit]: https://conventionalcommits.org
[example]: https://github.com/bluefireteam/audioplayers/tree/main/packages/audioplayers/example

### CODE REVIEW

**Comment by blaugold** [comment]
I'll try it out :)

**Comment by blaugold** [comment]
OK, I've tried #1469, and while it does make the issue I'm having less likely it still happens sometimes.

**Comment by blaugold** [comment]
@Gustl22 Friendly ping. Is there anything else I need to do?

**Comment by Gustl22** [comment]
I'll also try your branch ;) But I also wonder, what is the technical reason to avoid stutter, when setting the position before playing.

**Review by Gustl22 — APPROVED** [review]

**Comment by Gustl22** [comment]
@blaugold Thank you very much for your contribution!

**Pull request merged**
