### PR TITLE
feat(example): update app icons

### PR DESCRIPTION
**Pull request by Gustl22**
# Description

I created a logo for our library (or mostly for the exapmle app) in style of the Flutter logo. Idk if you more want sth that matches the Flame logo. E.g. a burning note (?).
Or we can change it again, if we crave for sth better :)

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:`, `chore:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation and added dartdoc comments with `///`, where necessary.
- [x] I have updated/added relevant examples in [example].

## Breaking Change

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

## Related Issues

[issue database]: https://github.com/bluefireteam/audioplayers/issues
[Contributor Guide]: https://github.com/bluefireteam/audioplayers/blob/main/contributing.md#feature-requests--prs
[Conventional Commit]: https://conventionalcommits.org
[example]: https://github.com/bluefireteam/audioplayers/tree/main/packages/audioplayers/example

### CODE REVIEW

**Comment by spydon** [comment]
Woooow, looks great!
I don't think it has to look like Flame since it is completely separate from flame. :)

**Review by spydon — APPROVED** [review]

**Review by erickzanardo — APPROVED** [review]
Love it! You should put it on the readme too :D

**Review by renancaraujo — APPROVED** [review]
Love it!

**Comment by Gustl22** [comment]
Unfortunately CSS styling is not a thing in GH, so I have to add the text in the logo itself. I tried many combinations, and as the name is that long, it looks weird to put it under the icon, so I put it next to it like done on Flutter itself.
You can preview [README here](https://github.com/bluefireteam/audioplayers/blob/129e90b27b0265b25fff0bc252d515fd01d4ab2e/README.md), as the link to the logo is not yet existant (only after merging) to provide absolute paths due to the monorepos subpackages.

|Compact|Horizontal|Vertical|
|---|---|---|
| logo_ap_compact | logo_ap_horizontal | logo_ap_vertical |

**Comment by spydon** [comment]
> Unfortunately CSS styling is not a thing in GH, so I have to add the text in the logo itself. I tried many combinations, and as the name is that long, it looks weird to put it under the icon, so I put it next to it like done on Flutter itself. You can preview [README here](https://github.com/bluefireteam/audioplayers/blob/129e90b27b0265b25fff0bc252d515fd01d4ab2e/README.md), as the link to the logo is not yet existant (only after merging) to provide absolute paths due to the monorepos subpackages.
> Compact 	Horizontal 	Vertical
> logo_ap_compact 	logo_ap_horizontal 	logo_ap_vertical

Nice, the first one is my favourite!
Make sure to store both the logo separately and the logo with text in the repo so that we can use them as fitting in different contexts.

**Comment by erickzanardo** [comment]
First one is my favorite as well!

**Comment by Gustl22** [comment]
For me personally or from Design perspective I think the second variant is best for the README header as it states the package name more clearly and possibly bringing less confusion to the users.
But I'm also happy to change it to the first variant! Won't make much of a difference in the end. I can add the other ones as well for completeness. I always provide vector files, which can be manipulated as desired.

Only for [clearing the terms](https://creativemarket.com/blog/logo-design-terms):
icon - the icon / brand itself
logo - the brand mostly with text

**Comment by Gustl22** [comment]
Changed to **compact** logo. Looks quite clear too :)

**Review by wolfenrain — APPROVED** [review]

**Comment by luanpotter** [comment]
OMG this is so awesome

**Pull request merged**
