### PR TITLE
refactor: Lint Kotlin, C and C++ code

### PR DESCRIPTION
**Pull request by Gustl22**
# Description

Test Linting Github Action Super Linter, to uniform source code:
https://github.com/marketplace/actions/super-linter

## Checklist

- [ ] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `refactor:`,
      `docs:`, `chore:`, `test:`, `ci:` etc).
- [ ] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.
- [ ] I have updated/added relevant documentation and added dartdoc comments with `///`, where necessary.
- [ ] I have updated/added relevant examples in [example].

## Breaking Change

- [ ] Yes, this is a breaking change.
- [ ] No, this is *not* a breaking change.

## Related Issues

#1587

[issue database]: https://github.com/bluefireteam/audioplayers/issues
[Contributor Guide]: https://github.com/bluefireteam/audioplayers/blob/main/contributing.md#feature-requests--prs
[Conventional Commit]: https://conventionalcommits.org
[example]: https://github.com/bluefireteam/audioplayers/tree/main/packages/audioplayers/example

### CODE REVIEW

**Review by spydon — APPROVED** [review]

**Review by luanpotter — APPROVED** [review]
YES YES YES!
I love this.

**Comment by luanpotter** [comment]
we need to add this to gamepads as well

**Comment by luanpotter** [comment]
we should consider adding instructions to our CONTRIBUTING files on how to run these linters separately locally though

**Comment by Gustl22** [comment]
I'll try to also implement it for Swift, and add the linting setup then.

**Pull request merged**
